### ISSUE TITLE
Error running pipeline

### ISSUE THREAD

**Issue by jayhesselberth** [hesselberthlab/twoprime#1]
From @lkwhite:

```
whitel@amc-tesla ~/twoprime/pipeline
$ snakemake -npr snakemaster.sh 
KeyError in line 14 of /vol2/home/whitel/twoprime/pipeline/Snakefile:
'FASTA'
  File "/vol2/home/whitel/twoprime/pipeline/Snakefile", line 14, in <module>
```

Notes from troubleshooting:
- making my own test Snakefile and running it as in your Rep. Research examples works fine
- played around with commenting out lines in the Snakefile; it's just the config lines throwing errors
- this comment from the Google Groups archive suggests the problem may be cluster specific but I don't fully understand that comment
- so I tried the same thing logged into a compute node and on the head node, but no dice

**Comment by jayhesselberth** [comment]
`snakemaster.sh` isn't mean to be run that way.

You can either submit the job:

```bash
bsub < snakemaster.sh
```

or run the pipeline from the command line (if you're in the same directory as the Snakefile:

```bash
snakemake -npr --configfile ribometh-seq-config.yml
```

**Comment by lkwhite** [comment]
Thanks. Understanding Snakemake without ever having built a makefile before is surprisingly opaque even when I get the general gist of what it's meant to accomplish.
