### ISSUE TITLE
Pipeline failing at or immediately after align call

### ISSUE THREAD

**Issue by lkwhite** [hesselberthlab/twoprime#2]
Still just trying to get this to run again on the Birkedal data. Last time the pipeline ran successfully was January 2016.

**Error log**
```
[E::hts_open_format] fail to open file 'alignment/SRR1158613.temp'
[bam_sort_core] fail to open 'alignment/SRR1158613.temp': No such file or directory
[bam_sort] Note the <out.prefix> argument has been replaced by -T/-o options
bowtie2-align died with signal 13 (PIPE) 
Error in job align while creating output file alignment/SRR1158613/SRR1158613.bam.
RuleException:
CalledProcessError in line 19 of /vol2/home/whitel/twoprime/pipeline/rules/coverage.snake:
Command 'bowtie2 --local -x /vol3/home/jhessel/ref/genomes/sacCer1/sacCer1 -U raw/SRR1158613.fastq.gz -p 8 | samtools view -F4 -bhu - | samtools sort -o - alignment/SRR1158613.temp -m 8G > alignment/SRR1158613/SRR1158613.bam' returned non-zero exit status 1
  File "/vol2/home/whitel/twoprime/pipeline/rules/coverage.snake", line 19, in __rule_align
  File "/vol1/software/modules-python/python3/3.4.0/lib/python3.4/concurrent/futures/thread.py", line 54, in run
Removing output files of failed job align since they might be corrupted:
alignment/SRR1158613/SRR1158613.bam
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

- Line 19 of [coverage.snake](https://github.com/hesselberthlab/twoprime/blob/master/pipeline/rules/coverage.snake) is the final line of the align call that generates sorted output from Samtools and a Samtools-generated index file. (I'm not sure where the resulting .bai file is used, so I briefly tried commenting out that second part of the line from the && onward to see if it changed anything. Nope.)
- thread.py is part of the concurrent.futures python module, used in [launching parallel tasks](https://docs.python.org/3/library/concurrent.futures.html).
- That signal 13 (PIPE) error from the aligner led me down a bit of a rabbit hole about errors we'd expect if we were running a newer version of Bowtie2 on Tesla (since the most recent version requires an explicit flag for the output), so I stuck a ```-``` in just before the pipe to samtools and the aligner got a little farther and actually dumped out one alignment into a file called ```-```.
- Does the bowtie2-align output need some kind of wildcard name?

**Comment by jayhesselberth** [comment]
Looks like that is caused by an old samtools sort invocation. I updated the samtools sort call in https://github.com/hesselberthlab/twoprime/commit/a02095ee8d0d4842eb8e8f33566795f695fb6610

Try that out.

**Comment by lkwhite** [comment]
Thanks for the fix; appears to be running now.
